### ISSUE TITLE
nitpick: delete logic will panic after create logic

### ISSUE THREAD

**Issue by cf250024** [viveksinghggits/ekspose#1]
I guess https://github.com/viveksinghggits/ekspose/blob/master/controller.go#L92 needs to return error. Otherwise the delete flow continues and it has panic with error.

Of course this is lab exercise for understanding the concepts and it is a well designed lab indeed. Just wonder why the item was dequeued by Forget(), how come it still shows up in delete logic?

**Comment by viveksinghggits** [comment]
Hi @cf250024, 
I agree, there are a lot of things that can be improved for example the thing that you mentioned must be changed. Another example is we don't even need `depLabels` function we could have just used that in the service spec itself.
I will make these changes in the next video.
I didnt actually understand what do you mean by second sentence.

**Comment by cf250024** [comment]
It was my bad for the second sentence. The delete function adds an object to the queue as well. That's why processItem() gets triggered as well.

Keep up for the good work!
